# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Semantic Release
on:
  push:
    branches: [ main ]

jobs:
  release:
    # https://github.community/t/how-do-i-specify-job-dependency-running-in-another-workflow/16482
    if: |
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      github.repository == 'community-fabric/python-ipfabric' &&
      !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install poetry --upgrade pip
          poetry config virtualenvs.create false
          poetry config experimental.new-installer false
          poetry install

      - name: Semantic Release
        env:
          PYPI_TOKEN: ${{ secrets.PYPI }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          semantic-release publish -D commit_author="github-actions <action@github.com>"
